# Generated by Django 4.2.11 on 2024-06-11 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourprojects',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='category'),
            preserve_default=False,
        ),
    ]
