# Generated by Django 4.2.11 on 2024-06-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ourprojects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourprojects',
            name='slug',
            field=models.SlugField(default='hello', max_length=150, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
