# Generated by Django 4.2.11 on 2024-07-18 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_about_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantagesService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='main.services')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
