# Generated by Django 4.2.11 on 2024-07-18 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_advantagesservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.ImageField(upload_to='media/services/icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'jpg', 'png'])], verbose_name='icon images'),
        ),
    ]
